import { store } from "@/redux-store/store";
import { setCategories } from "@/redux-store/sliceCategories";
import { setTags } from "@/redux-store/sliceTags";
import ReduxProvider from '@/redux-store/provider/ReduxProvider'
import SyncStoreWithClient from "@/redux-store/sync/SyncStoreWithClient";
import Header from "@/components/Header";
// import Categories from '@/components/Categories'
// import Tags from '@/components/Tags'
import { filterUncategorized } from "@/utils/converters";
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getCategories() {
  const res = await fetch(`${process.env.API_ENDPOINT}categories`);
  return res.json();
}

async function getTags() {
  const res = await fetch(`${process.env.API_ENDPOINT}tags?per_page=100`);
  return res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const categoriesData = getCategories();
  const tagsData = getTags();

  let [categories, tags] = await Promise.all([categoriesData, tagsData]);
  categories = filterUncategorized(categories)

  store.dispatch(setCategories(categories))
  store.dispatch(setTags(tags))

  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <SyncStoreWithClient categories={categories} tags={tags} />
          <Header dark={false} changeTheme={false} />
          <main>
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  )
}
