import ReduxProvider from '@/redux-store/provider/ReduxProvider'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>This is the layout</h1>
        </header>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
